tests:
  node:
    default:
      description: Verify that node runs and returns a version
      environment:
        APP_ENV: "development"
      goss_config:
        command:
          node -v:
            exit-status: 0
            stdout:
              - v14.16.1
            timeout: 10000
  php:
    xdebug_disabled:
      description: Verify that PHP_DEBUG=0 disables the xdebug module.
      environment:
        PHP_DEBUG: 0
        APP_ENV: "development"
      goss_config:
        command:
          php -i | grep xdebug:
            exit-status: 0
            stdout:
              - !xdebug
            timeout: 10000
    newrelic_enabled:
      description: Verify that passing a license key and NEWRELIC_ENABLED=1 enables the newrelic module.
      environment:
        NEWRELIC_ENABLED: 1
        NEWRELIC_LICENSE_KEY: "1234567890"
        APP_ENV: "development"
      goss_config:
        command:
          php -i:
            exit-status: 0
            stdout:
              - newrelic
            timeout: 10000
    newrelic_disabled:
      description: Verify that newrelic is disabled by default.
      environment:
        APP_ENV: "development"
      goss_config:
        command:
          php -i:
            exit-status: 0
            stdout:
              - !newrelic
            timeout: 10000
